apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f users/topin/banger/docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: influxdb
status:
  loadBalancer: {}
