version : '3'
	service:
		
		
		
		
		
version : '3'
	service:
		
		
version : '3'
	service:
		
		
version : '3'
	service:
		
		
		
		
		
		
version : '3'
	service:
		
		
		
		
		
		
version : '3'
	service:
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
version : '3'
	service:
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
version : '3'
	service:
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
version : '3'
	service:
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
