version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    hostname: influxdb
    volumes:
    - .influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    depends_on:
    - influxdb
    container_name: grafana
    restart: always
    ports:
    - 3000:3000
    links:
    - influxdb:influxdb
    volumes:
    - ./grafana:/var/lib/grafana
  telegraf:
    image: telegraf
    depends_on:
    - influxdb
    container_name: telegraf
    restart: always
    links:
    - influxdb:influxdb
    tty: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
